Update default.scss
Because of an error of CI found in: https://github.com/owncloud/files_mediaviewer/pull/481

```
ERROR in ./src/styles/default.scss (./node_modules/css-loader/dist/cjs.js!./node_modules/sass-loader/dist/cjs.js!./src/styles/default.scss)
    Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
    SassError: Can't find stylesheet to import.
       │
    26 │     @import "../../node_modules/swiper/dist/css/swiper.min";
       │             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

This should be corrected:

`node_modules/swiper/dist/css/swiper.min` --> `node_modules/swiper/dist/css/swiper.min.css`